name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Set up Python 3.13
        run: |
          uv python install 3.13
          uv python pin 3.13

      - name: Install dependencies
        run: |
          uv sync

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            if [ ! -d "~/bbs-mainframe" ]; then
              git clone https://github.com/t3tra-dev/bbs-mainframe.git ~/bbs-mainframe
            else
              cd ~/bbs-mainframe
              git pull
            fi

            cd ~/bbs-mainframe

            uv sync

            nohup uv run uvicorn main:app --host 0.0.0.0 --port 8000 &
